name: CI Pipeline

on:
  push:
    branches: [main]  # Ejecuta el CI cuando hay un push a la rama main
  pull_request:
    branches: [main]  # También en los PR hacia la rama main

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}  # Corre en múltiples sistemas operativos

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Soporte multiplataforma
        python-version: [3.9, 3.10, 3.11]                   # Pruebas con varias versiones de Python

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Clona el repo

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linter
      run: |
        flake8 src tests  # Linter para verificar estilo de código

    - name: Run tests
      run: |
        pytest  # Corre las pruebas unitarias